version: "3.7"

services:
  unbound:
    image: klutchell/unbound:latest
    ports:
      - 5053:53/udp
      - 5053:53
    networks:
      - traefik

  pihole:
    image: pihole/pihole:latest
    volumes:
      - pihole:/etc/pihole
      - dnsmasq:/etc/dnsmasq.d
    depends_on:
      - unbound
    environment:
      - TZ=America/Los_Angeles
      - PIHOLE_DNS_=172.18.0.1#5053 #replace with docker_gwbridge's gateway ip
      - REV_SERVER=true
      - REV_SERVER_CIDR=192.168.1.0/24 #Update these fields to match your environment
      - REV_SERVER_TARGET=192.168.1.1
      - REV_SERVER_DOMAIN=home
      - WEBPASSWORD_FILE=/run/secrets/pihole_webpw
    secrets:
      - pihole_webpw
    networks:
      - traefik
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.piholeweb.rule=Host(`pihole.home`)
        - traefik.http.routers.piholeweb.entrypoints=web
        - traefik.http.services.piholeweb.loadbalancer.server.port=80
        # 53/udp
        - traefik.udp.routers.pihole-dns-udp.entrypoints=dns-udp
        - traefik.udp.routers.pihole-dns-udp.service=pihole-dns-udp
        - traefik.udp.services.pihole-dns-udp.loadbalancer.server.port=53
        # 53/tcp
        - traefik.tcp.routers.pihole-dns-tcp.rule=HostSNI(`*`)
        - traefik.tcp.routers.pihole-dns-tcp.entrypoints=dns-tcp
        - traefik.tcp.routers.pihole-dns-tcp.service=pihole-dns-tcp
        - traefik.tcp.services.pihole-dns-tcp.loadbalancer.server.port=53

networks:
  traefik:
    external: true

volumes:
  pihole:
  dnsmasq:

secrets:
  pihole_webpw:
    external: true