entryPoints:
  web:
    address: ':80'
  dns-tcp:
    address: ':53'
  dns-udp:
    address: ':53/udp'

providers:
  docker:
    swarmMode: true
    exposedByDefault: false
    network: traefik

api:
  insecure: true

metrics:
  influxDB:
    address: telegraf:8089
    protocol: udp
    database: "traefik"
    addEntryPointsLabels: true 
    addServicesLabels: true
    pushInterval: 10s

log:
  level: ERROR