version: "3.8"
services:
  wireguard:
    image: weejewel/wg-easy:5
    cap_add:
      - CAP_NET_ADMIN
      - CAP_SYS_MODULE
    environment:
      - WG_HOST=wg.yourdomain.com #update with your domain
      - PASSWORD=yourpassword #update with your password
      - WG_DEFAULT_DNS=1.1.1.1
      - WG_PERSISTENT_KEEPALIVE=15
    volumes:
      - wireguard_config:/etc/wireguard
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    ports:
      - target: 51820
        published: 51820
        protocol: udp
        mode: host
      - target: 51821
        published: 51821
        protocol: tcp
        mode: host
    networks:
      - bridge

volumes:
  wireguard_config:

networks:
  bridge:
   external: true
   name: bridge
